# Generated by Django 4.0.5 on 2022-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureSerre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_time', models.DateTimeField(verbose_name='date received')),
                ('temperature_celsius', models.FloatField()),
            ],
        ),
    ]
